import Head from "next/head";

import About from "../src/components/About";
import Hero from "../src/components/Hero";
import Services from "../src/components/Services";
import Skills from "../src/components/Skills";
import Layout from "../src/components/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vedat Kokmen || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Layout>
        <Hero />
        <About />
        <Services />
        <Skills />
      </Layout>
    </div>
  );
}
